language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -U pip
  - pip install .[test,qa] wheel
script:
  - pytest
  - flake8 frontmark
  - python setup.py bdist_wheel
