language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -U pip
  - pip install -U  -e .[test,qa] wheel python-coveralls
script:
  - pytest --cov frontmark
  - flake8 frontmark
  - python setup.py bdist_wheel
after_success:
  - coveralls
